version: "2"
services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        restart: always
        depends_on:
            - php
        ports:
            - "82:80"
        networks:
            - default

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /app
        env_file: .env
        restart: always
        expose:
            - "9000"
